// Mocks generated by Mockito 5.4.0 from annotations
// in cook_app/test/modules/home/infra/repositories/get_recipes_list_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:cook_app/modules/home/infra/datasources/get_recipes_list_datasource.dart'
    as _i2;
import 'package:cook_app/modules/home/infra/models/recipe_model.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetRecipeDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRecipeDatasource extends _i1.Mock
    implements _i2.GetRecipeDatasource {
  @override
  _i3.Future<List<_i4.RecipeModel>> getRecipesList() => (super.noSuchMethod(
        Invocation.method(
          #getRecipesList,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.RecipeModel>>.value(<_i4.RecipeModel>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.RecipeModel>>.value(<_i4.RecipeModel>[]),
      ) as _i3.Future<List<_i4.RecipeModel>>);
}
