// Mocks generated by Mockito 5.4.0 from annotations
// in cook_app/test/modules/home/domain/usecases/get_recipes_list_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cook_app/modules/home/domain/entities/recipe.dart' as _i6;
import 'package:cook_app/modules/home/domain/errors/errors.dart' as _i5;
import 'package:cook_app/modules/home/domain/repositories/get_recipes_list_repository.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetRecipeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRecipeRepository extends _i1.Mock
    implements _i3.GetRecipeRepository {
  @override
  _i4.Future<_i2.Either<_i5.FailureHome, List<_i6.Recipe>>> getRecipesList() =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecipesList,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.FailureHome, List<_i6.Recipe>>>.value(
                _FakeEither_0<_i5.FailureHome, List<_i6.Recipe>>(
          this,
          Invocation.method(
            #getRecipesList,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.FailureHome, List<_i6.Recipe>>>.value(
                _FakeEither_0<_i5.FailureHome, List<_i6.Recipe>>(
          this,
          Invocation.method(
            #getRecipesList,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.FailureHome, List<_i6.Recipe>>>);
}
